"attribute" = "creamsicle"
"type" = "creamsicle"
# "type.builtin"
# "type.enum"
"type.enum.variant" = "sky"
"constructor" = "goddess"
"constant" = "sky"
# "constant.builtin"
# "constant.builtin.boolean"
# "constant.character"
"constant.character.escape" = "blueberry"
# "constant.numeric"
# "constant.numeric.integer"
# "constant.numeric.float"
"string" = "sour_apple"
"string.regexp" = "blueberry"
"string.special" = "blueberry"
"string.special.path" = "peacock"
"string.special.url" = { fg = "peacock", underline = { color = "peacock", style = "line" } }
"string.special.symbol" = "blueberry"
"comment" = "elephant"
# "comment.line"
"comment.line.documentation" = "chalk"
# "comment.block"
"comment.block.documentation" = "chalk"
"comment.unused" = { modifiers = ["dim"] }
"variable" = "peach"
"variable.builtin" = "princess"
"variable.parameter" = "coral"
"variable.other" = "cherry_blossom"
# "variable.other.member"
# "variable.other.member.private"
"label" = "goddess"
"punctuation" = "honeycomb"
# "punctuation.delimiter"
# "punctuation.bracket"
"punctuation.special" = "strawberry"
"keyword" = "strawberry"
# "keyword.control"
# "keyword.control.conditional"
# "keyword.control.repeat"
# "keyword.control.import"
# "keyword.control.return"
# "keyword.control.exception"
# "keyword.operator"
# "keyword.directive"
# "keyword.function"
# "keyword.storage"
# "keyword.storage.type"
# "keyword.storage.modifier"
"operator" = "honeycomb"
"function" = "lilac"
# "function.builtin"
# "function.method"
# "function.method.private"
# "function.macro"
# "function.special"
"tag" = "sand"
# "tag.builtin"
"namespace" = "sand"
"special" = "princess"
# "markup"
# "markup.normal"
# "markup.normal.completion"
# "markup.normal.hover"
"markup.heading" = { fg = "cherry_blossom", modifiers = ["bold"] }
# "markup.heading.marker"
"markup.heading.1" = { fg = "cherry_blossom", modifiers = ["bold"] }
"markup.heading.2" = { fg = "coral", modifiers = ["bold"] }
"markup.heading.3" = { fg = "sand", modifiers = ["bold"] }
"markup.heading.4" = { fg = "creamsicle", modifiers = ["bold"] }
"markup.heading.5" = { fg = "sour_apple", modifiers = ["bold"] }
"markup.heading.6" = { fg = "goddess", modifiers = ["bold"] }
# "markup.heading.completion"
# "markup.heading.hover"
"markup.list" = "honeycomb"
# "markup.list.unnumbered"
# "markup.list.numbered"
"markup.list.checked" = "sour_apple"
"markup.list.unchecked" = "elephant"
"markup.bold" = { fg = "lilac", modifiers = ["bold"] }
"markup.italic" = { fg = "sky", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { fg = "peacock", underline = { color = "peacock", style = "line" } }
"markup.link.url" = { fg = "peacock", underline = { color = "peacock", style = "line" } }
"markup.link.label" = "goddess"
"markup.link.text" = "goddess"
"markup.quote" = "peach"
"markup.raw" = "sour_apple"
# "markup.raw.inline"
# "markup.raw.inline.completion"
# "markup.raw.inline.hover"
# "markup.raw.block"
# "diff"
"diff.plus" = "sour_apple"
# "diff.plus.gutter"
"diff.minus" = "strawberry"
# "diff.minus.gutter"
"diff.delta" = "sky"
"diff.delta.moved" = "peacock"
"diff.delta.conflict" = "sand"
# "diff.delta.gutter"
"ui.background" = { bg = "blackboard" }
"ui.background.separator" = "cherry_blossom"
# "ui.cursor"
"ui.cursor.normal" = { bg = "opium", fg = "raven", modifiers = ["bold"] }
"ui.cursor.insert" = { bg = "sage", fg = "raven", modifiers = ["bold"] }
"ui.cursor.select" = { bg = "cloud", fg = "raven", modifiers = ["bold"] }
"ui.cursor.match" = { fg = "lemon", modifiers = ["bold"], underline = { color = "lemon", style = "line" } }
# "ui.cursor.primary"
"ui.cursor.primary.normal" = { bg = "cherry_blossom", fg = "raven", modifiers = [
  "bold",
] }
"ui.cursor.primary.insert" = { bg = "sour_apple", fg = "raven", modifiers = [
  "bold",
] }
"ui.cursor.primary.select" = { bg = "sky", fg = "raven", modifiers = ["bold"] }
"ui.debug.breakpoint" = "princess"
"ui.debug.active" = "cherry_blossom"
# "ui.gutter"
# "ui.gutter.selected"
"ui.linenr" = "soil"
"ui.linenr.selected" = { fg = "peach", modifiers = ["bold"] }
"ui.statusline" = { bg = "film", fg = "chalk" }
"ui.statusline.inactive" = "elephant"
"ui.statusline.normal" = { bg = "cherry_blossom", fg = "raven" }
"ui.statusline.insert" = { bg = "sour_apple", fg = "raven" }
"ui.statusline.select" = { bg = "sky", fg = "raven" }
"ui.statusline.separator" = { fg = "creamsicle", modifiers = ["bold"] }
"ui.bufferline" = { fg = "elephant" }
"ui.bufferline.active" = { fg = "cherry_blossom", modifiers = ["bold"], underline = { color = "cherry_blossom", style = "double_line" } }
"ui.bufferline.background" = { bg = "raven" }
"ui.popup" = { bg = "cocoa", fg = "nectarine" }
# "ui.popup.info"
# "ui.picker.header"
# "ui.picker.header.column"
"ui.picker.header.column.active" = { modifiers = ["bold"], underline = { color = "cherry_blossom", style = "line" } }
"ui.window" = "cherry_blossom"
"ui.help" = { bg = "cocoa", fg = "nectarine" }
"ui.text" = "chalk"
"ui.text.focus" = { bg = "ink" }
"ui.text.inactive" = { fg = "elephant" }
# "ui.text.info"
"ui.text.directory" = "creamsicle"
"ui.virtual.ruler" = { bg = "charcoal" }
"ui.virtual.whitespace" = "soil"
"ui.virtual.indent-guide" = "soil"
"ui.virtual.inlay-hint" = { bg = "blackboard", fg = "soil", modifiers = [
  "italic",
] }
# "ui.virtual.inlay-hint.parameter"
# "ui.virtual.inlay-hint.type"
"ui.virtual.wrap" = "soil"
"ui.virtual.jump-label" = { fg = "lemon", modifiers = ["bold", "italic"] }
"ui.menu" = { bg = "film" }
"ui.menu.selected" = { fg = "cherry_blossom", modifiers = ["bold"], underline = { color = "cherry_blossom", style = "line" } }
"ui.menu.scroll" = "cherry_blossom"
"ui.selection" = { bg = "asphalt" }
"ui.selection.primary" = { bg = "sea" }
"ui.highlight" = { bg = "sea" }
"ui.highlight.frameline" = { bg = "date" }
"ui.cursorline.primary" = { bg = "ink" }
# "ui.cursorline.secondary"
"ui.cursorcolumn.primary" = { bg = "ink" }
# "ui.cursorcolumn.secondary"
"warning" = { fg = "lantern", modifiers = ["italic"] }
"error" = { fg = "salsa", modifiers = ["italic"] }
"info" = { fg = "orchid", modifiers = ["italic"] }
"hint" = { fg = "chalk", modifiers = ["italic"] }
"diagnostic" = { underline = { color = "chalk", style = "curl" } }
"diagnostic.hint" = { underline = { color = "chalk", style = "curl" } }
"diagnostic.info" = { underline = { color = "orchid", style = "curl" } }
"diagnostic.warning" = { underline = { color = "lantern", style = "curl" } }
"diagnostic.error" = { underline = { color = "salsa", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"tabstop" = { modifiers = ["italic"] }
"rainbow" = [
  "honeycomb",
  "sand",
  "strawberry",
  "cherry_blossom",
  "lilac",
  "sky",
]

[palette]
blackboard = "#181716"
strawberry = "#f76f80"
sour_apple = "#bec975"
honeycomb = "#e8d6a7"
lilac = "#caa2ca"
cherry_blossom = "#e5a1a3"
sky = "#a5b6ce"
elephant = "#88847f"
soil = "#73665b"
sand = "#f98959"
goddess = "#a2caa0"
creamsicle = "#f7bb6c"
blueberry = "#9e9fec"
princess = "#fa7fb5"
peacock = "#8accc7"
chalk = "#d5d0c9"
peach = "#e4b99d"
coral = "#fa9485"
raven = "#0a0909"
ink = "#111010"
cocoa = "#1f1e1b"
date = "#210f11"
film = "#2e2a27"
charcoal = "#313735"
asphalt = "#433a31"
sea = "#0f3f4e"
opium = "#978182"
sage = "#878972"
cloud = "#808387"
orchid = "#ec89ed"
nectarine = "#f1d090"
salsa = "#f7524c"
lantern = "#f7bf32"
lemon = "#ffef43"
