"attribute" = "creamsicle"
"type" = "creamsicle"
# "type.builtin"
# "type.enum"
# "type.enum.variant"
"constructor" = "lilac"
"constant" = "sky"
# "constant.builtin"
# "constant.builtin.boolean"
# "constant.character"
# "constant.character.escape"
# "constant.numeric"
# "constant.numeric.integer"
# "constant.numeric.float"
"string" = "sour_apple"
"string.regexp" = "lilac"
"string.special" = "blueberry"
"string.special.path" = "peacock"
"string.special.url" = { fg = "peacock", underline.style = "line" }
"string.special.symbol" = "blueberry"
"comment" = "elephant"
# "comment.line"
# "comment.line.documentation"
# "comment.block"
# "comment.block.documentation"
# "comment.unused"
"variable" = "cherry_blossom"
# "variable.builtin"
# "variable.parameter"
# "variable.other"
# "variable.other.member"
# "variable.other.member.private"
"label" = "goddess"
"punctuation" = "honeycomb"
# "punctuation.delimiter"
# "punctuation.bracket"
"punctuation.special" = "strawberry"
"keyword" = "strawberry"
# "keyword.control"
# "keyword.control.conditional"
# "keyword.control.repeat"
# "keyword.control.import"
# "keyword.control.return"
# "keyword.control.exception"
# "keyword.operator"
# "keyword.directive"
# "keyword.function"
# "keyword.storage"
# "keyword.storage.type"
# "keyword.storage.modifier"
"operator" = "honeycomb"
"function" = "lilac"
# "function.builtin"
# "function.method"
# "function.method.private"
# "function.macro"
# "function.special"
"tag" = "salmon"
# "tag.builtin"
"namespace" = "salmon"
"special" = "princess"
# "markup"
# "markup.normal"
# "markup.normal.completion"
# "markup.normal.hover"
# "markup.heading"
"markup.heading" = "cherry_blossom"
# "markup.heading.marker"
# "markup.heading.1"
# "markup.heading.2"
# "markup.heading.3"
# "markup.heading.4"
# "markup.heading.5"
# "markup.heading.6"
# "markup.heading.completion"
# "markup.heading.hover"
"markup.list" = "sky"
# "markup.list.unnumbered"
# "markup.list.numbered"
# "markup.list.checked"
# "markup.list.unchecked"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
# "markup.link"
"markup.link.url" = { fg = "peacock", underline.style = "line" }
"markup.link.label" = "peacock"
"markup.link.text" = "lilac"
"markup.quote" = "elephant"
"markup.raw" = "sour_apple"
# "markup.raw.inline"
# "markup.raw.inline.completion"
# "markup.raw.inline.hover"
# "markup.raw.block"
# "diff"
"diff.plus" = "sour_apple"
# "diff.plus.gutter"
"diff.minus" = "strawberry"
# "diff.minus.gutter"
"diff.delta" = "sky"
"diff.delta.moved" = "creamsicle"
"diff.delta.conflict" = "lilac"
# "diff.delta.gutter"
"ui.background" = { bg = "blackboard" }
"ui.background.separator" = "cherry_blossom"
# "ui.cursor"
"ui.cursor.normal" = { bg = "opium", fg = "blackboard" }
"ui.cursor.insert" = { bg = "sage", fg = "blackboard" }
"ui.cursor.select" = { bg = "cloud", fg = "blackboard" }
"ui.cursor.match" = { fg = "lemon", modifiers = ["bold"], underline.style = "line" }
# "ui.cursor.primary"
"ui.cursor.primary.normal" = { bg = "cherry_blossom", fg = "blackboard" }
"ui.cursor.primary.insert" = { bg = "sour_apple", fg = "blackboard" }
"ui.cursor.primary.select" = { bg = "sky", fg = "blackboard" }
"ui.debug.breakpoint" = "princess"
"ui.debug.active" = "princess"
# "ui.gutter"
# "ui.gutter.selected"
"ui.linenr" = "elephant"
"ui.linenr.selected" = { fg = "cherry_blossom", modifiers = ["bold"] }
"ui.statusline" = { bg = "film", fg = "chalk" }
"ui.statusline.inactive" = { modifiers = ["dim"] }
"ui.statusline.normal" = { bg = "cherry_blossom", fg = "blackboard" }
"ui.statusline.insert" = { bg = "sour_apple", fg = "blackboard" }
"ui.statusline.select" = { bg = "sky", fg = "blackboard" }
"ui.statusline.separator" = { modifiers = ["bold"] }
"ui.bufferline" = { fg = "elephant" }
"ui.bufferline.active" = { fg = "cherry_blossom", underline.style = "line" }
"ui.bufferline.background" = { bg = "blackboard" }
"ui.popup" = { fg = "creamsicle" }
"ui.popup.info" = { bg = "film", fg = "creamsicle" }
# "ui.picker.header"
# "ui.picker.header.column"
"ui.picker.header.column.active" = { modifiers = ["bold"], underline = { color = "cherry_blossom", style = "line" } }
"ui.window" = "cherry_blossom"
"ui.help" = { fg = "honeycomb", bg = "film" }
"ui.text" = "chalk"
"ui.text.focus" = { bg = "metal" }
"ui.text.inactive" = { fg = "elephant" }
"ui.text.info" = "honeycomb"
"ui.text.directory" = "creamsicle"
"ui.virtual.ruler" = { bg = "charcoal" }
"ui.virtual.whitespace" = "soil"
"ui.virtual.indent-guide" = "soil"
"ui.virtual.inlay-hint" = { fg = "soil", modifiers = ["italic"] }
# "ui.virtual.inlay-hint.parameter"
# "ui.virtual.inlay-hint.type"
"ui.virtual.wrap" = "elephant"
"ui.virtual.jump-label" = { fg = "lemon", modifiers = ["bold", "italic"] }
"ui.menu" = { bg = "film" }
"ui.menu.selected" = { fg = "cherry_blossom", modifiers = ["bold"], underline = { color = "cherry_blossom", style = "line" } }
"ui.menu.scroll" = { bg = "film", fg = "cherry_blossom" }
"ui.selection" = { bg = "asphalt" }
"ui.selection.primary" = { bg = "sea" }
"ui.highlight" = { bg = "sea" }
"ui.highlight.frameline" = { bg = "date" }
"ui.cursorline.primary" = { bg = "metal" }
# "ui.cursorline.secondary"
"ui.cursorcolumn.primary" = { bg = "metal" }
# "ui.cursorcolumn.secondary"
"warning" = { bg = "film", fg = "creamsicle" }
"error" = { bg = "film", fg = "strawberry" }
"info" = { bg = "film", fg = "lilac" }
"hint" = { bg = "film", fg = "chalk" }
"diagnostic" = { underline = { color = "chalk", style = "curl" } }
"diagnostic.hint" = { underline = { color = "chalk", style = "curl" } }
"diagnostic.info" = { underline = { color = "lilac", style = "curl" } }
"diagnostic.warning" = { underline = { color = "creamsicle", style = "curl" } }
"diagnostic.error" = { underline = { color = "strawberry", style = "curl" } }
"diagnostic.unnecessary" = { underline = { color = "honeycomb", style = "dotted" } }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
# "tabstop" = { modifiers = ["italic"] }

[palette]
blackboard = "#181716"
strawberry = "#f56e7f"
sour_apple = "#bec975"
honeycomb = "#e8d6a7"
lilac = "#caa2ca"
cherry_blossom = "#e5a1a3"
sky = "#a5b6ce"
elephant = "#88847f"
soil = "#73665b"
salmon = "#f58669"
goddess = "#a2caa0"
creamsicle = "#f7bb6c"
blueberry = "#9293ec"
princess = "#ef7dc0"
peacock = "#5dccc3"
chalk = "#d5d0c9"
metal = "#212225"
date = "#210f11"
film = "#2e2a27"
charcoal = "#313735"
asphalt = "#43403d"
sea = "#0f3f4e"
opium = "#978182"
sage = "#878972"
cloud = "#808387"
nectarine = "#f1d090"
lemon = "#ffef43"
